FROM nginx
COPY . /usr/share/nginx/html

# Host static content by copying to a new image
# >> docker pull nginx
# >> docker build -t hello_nginx .
# >> cd to Dockerfile
# >> docker build -t hello_nginx .
